id: P010734
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD137841
  title: 中国第二历史档案馆所存西藏和藏事档案汇编
  author: ''
  volumes:
    c9b22cbfa195433fac10c29e557d7891:
      image_group_id: I2PD20448
      title: ''
      volume_number: 1
      total_pages: 574
      base_file: v001.txt
    a86f9d76ad274c3c82c4ba954724fa01:
      image_group_id: I2PD20449
      title: ''
      volume_number: 2
      total_pages: 550
      base_file: v002.txt
    b613de86a5df41ea814644e2fb3a4616:
      image_group_id: I2PD20450
      title: ''
      volume_number: 3
      total_pages: 506
      base_file: v003.txt
    621456df18c84f8a970edc0e21d46f06:
      image_group_id: I2PD20451
      title: ''
      volume_number: 4
      total_pages: 514
      base_file: v004.txt
    0399dcb24e2f466c9c091072cb271017:
      image_group_id: I2PD20452
      title: ''
      volume_number: 5
      total_pages: 514
      base_file: v005.txt
    f957b9ba6c124248a84c4ff990978698:
      image_group_id: I2PD20453
      title: ''
      volume_number: 6
      total_pages: 526
      base_file: v006.txt
    d3c253356fc8414cae54f3ae145f1a70:
      image_group_id: I2PD20454
      title: ''
      volume_number: 7
      total_pages: 518
      base_file: v007.txt
    064b36c7e56d4bb79c128bf5c369c9f4:
      image_group_id: I2PD20455
      title: ''
      volume_number: 8
      total_pages: 546
      base_file: v008.txt
    9283c717bd2346499e06050e508be931:
      image_group_id: I2PD20456
      title: ''
      volume_number: 9
      total_pages: 510
      base_file: v009.txt
    13982fdcbea141ebafc2cc38aa3f556c:
      image_group_id: I2PD20457
      title: ''
      volume_number: 10
      total_pages: 544
      base_file: v010.txt
    fe40bc63aa7240cd91c1c02f7e2dc614:
      image_group_id: I2PD20458
      title: ''
      volume_number: 11
      total_pages: 496
      base_file: v011.txt
    410dcfa95b81434593ab82947de45539:
      image_group_id: I2PD20459
      title: ''
      volume_number: 12
      total_pages: 506
      base_file: v012.txt
    c9afbb6391b44921a6910758d64dc411:
      image_group_id: I2PD20460
      title: ''
      volume_number: 13
      total_pages: 492
      base_file: v013.txt
    81c2d28db4914f7585e97f611545006f:
      image_group_id: I2PD20461
      title: ''
      volume_number: 14
      total_pages: 500
      base_file: v014.txt
    9a52ed001eb44b6ca27a67a25f39661e:
      image_group_id: I2PD20462
      title: ''
      volume_number: 15
      total_pages: 484
      base_file: v015.txt
    d21f2f56faef4a5682cf2a856feb7592:
      image_group_id: I2PD20463
      title: ''
      volume_number: 16
      total_pages: 502
      base_file: v016.txt
    4bc5c0d6a6f94cb584ee3bae7467c9d8:
      image_group_id: I2PD20464
      title: ''
      volume_number: 17
      total_pages: 508
      base_file: v017.txt
    ed1db304cc704378995f98c07a66ebdc:
      image_group_id: I2PD20465
      title: ''
      volume_number: 18
      total_pages: 500
      base_file: v018.txt
    4505b552b9fb45369b7c8857186ccfbc:
      image_group_id: I2PD20466
      title: ''
      volume_number: 19
      total_pages: 510
      base_file: v019.txt
    9f5ddfc484b843d8b54d7d4097e900ea:
      image_group_id: I2PD20467
      title: ''
      volume_number: 20
      total_pages: 504
      base_file: v020.txt
